version: "3.7"

services:  
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'

  api:
    container_name: crazy-picasso_backend
    build:
      dockerfile: "Dockerfile.dev"
      context: './server'
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      DB_CONNECTION: mongodb://mongo:27017/crazy-picasso_backend
    external_links:
      - mongo

  client:
    build:
      dockerfile: "Dockerfile.dev"
      context: './client'
    volumes:
      - /app/node_modules
      - ./client:/app
  
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodb-data:/data/db
    ports:
      - '27017:27017'

volumes:
   mongodb-data: